Repository rcos/observatory-new, pull requests merged in 2019-11, with the labels that each got.

#82 Improve password hashing API
  Cargo.toml
  src/auth/crypto.rs
  src/auth/handlers.rs
  src/fairings.rs
  src/main.rs
  src/tests.rs
  src/users/handlers.rs
  src/users/models.rs
Labels: enhancement, help wanted

#88 Small group meeting
  src/groups/handlers.rs
  templates/group/group.html
Labels: bug

#83 Groups folder documentation
  src/groups/handlers.rs
  src/groups/models.rs
  src/groups/templates.rs
Labels: enhancement

#96 Active filter for users and projects
  src/projects/handlers.rs
  src/projects/models.rs
  src/projects/templates.rs
  src/users/handlers.rs
  src/users/templates.rs
  templates/project/edit-project.html
  templates/project/new-project.html
  templates/project/projects-list.html
  templates/user/users-list.html
Labels: enhancement

#97 Delete relations when necessary
  src/attend/handlers.rs
  src/calendar/handlers.rs
  src/groups/handlers.rs
  src/projects/handlers.rs
  src/users/handlers.rs
  templates/calendar/event.html
Labels: bug

#99 Switch to GitHub Actions
  .circleci/config.yml
  .github/workflows/dockerimage.yml
  .github/workflows/rust.yml
  README.md
Labels: enhancement

#98 Reserved words and expanded FormError use
  src/auth/handlers.rs
  src/auth/templates.rs
  src/calendar/handlers.rs
  src/calendar/templates.rs
  src/groups/handlers.rs
  src/groups/templates.rs
  src/news/handlers.rs
  src/news/templates.rs
  src/projects/handlers.rs
  src/projects/templates.rs
  src/templates.rs
  src/users/handlers.rs
  src/users/templates.rs
  templates/form-error.html
  templates/group/edit-group.html
  templates/group/new-group.html
  templates/project/edit-project.html
  templates/project/new-project.html
  templates/user/edit-user.html
Labels: bug, enhancement

#102 Event attendees
  src/attend/models.rs
  src/calendar/handlers.rs
  src/calendar/models.rs
  src/calendar/templates.rs
  src/groups/handlers.rs
  src/main.rs
  templates/calendar/event.html
  templates/group/group.html
  templates/project/project.html
Labels: bug, enhancement
